# Generated by Django 3.0.2 on 2020-03-15 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_employee',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='register_employee',
            name='emp_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register_employee',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register_employee',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register_employee',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='New_Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('emp_id', models.CharField(max_length=10, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
